### PR TITLE
style: fix @typescript-eslint/camelcase rule

### PR DESCRIPTION
**Pull request by abdonrd**
Continue with #1343.

I'm going to add them here: #1759.

### CODE REVIEW

**Comment by abdonrd** [comment]
@starpit `type coverage regression` again. 🎊

**Comment by myan9** [comment]
Thanks Abdón! Do you think adding the option below would make sense? With the properties naming restriction, does it mean that every time we use packages that are not using this eslint rule, we need add the disable eslint line?
```
{
    "rules": {
        "camelcase": [2, {"properties": "never"}]
    }
}
```

**Comment by abdonrd** [comment]
@myan9 instead of disable all properties, I use the `allow` option with the external packages.

**Comment by starpit** [comment]
typecov issues fixed in #1817

**Pull request closed without merging**
