### PR TITLE
fix(plugins/plugin-carbon-themes) a11y - sidecar badge contrast fix

### PR DESCRIPTION
**Pull request by showeimer**
Fixes https://github.com/IBM/kui/issues/3151

---

#### Before:

Screen Shot 2020-02-10 at 10 48 19 AM
Screen Shot 2020-02-10 at 10 48 39 AM

---

#### After:

Screen Shot 2020-02-10 at 10 48 55 AM
Screen Shot 2020-02-10 at 10 49 18 AM

**DAP scan no longer flags contrast issue**

---

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

**Comment by showeimer** [comment]
@starpit why are there color css stylings in non-theme css files if theming is supported?  It seems like the theme css files should only have references to any color styling and all other css files should be only coded to handle layout and component structures.

**Comment by starpit** [comment]
for the most part, the core UI components are expressed relative to the "base16" class scheme. this is base00 through base0F. then, the primary job of a theme is to map those 16 color classes to color choices.

we have a few old css classes (such as the ones you have touched) that indirectly use the base16 scheme. over time, we hope to remove this indirection, and have all UI components reference the base16 scheme directly.

**Comment by showeimer** [comment]
@starpit moved fix to carbon-gray90 css file instead

**Comment by showeimer** [comment]
Screen Shot 2020-02-10 at 1 31 04 PM

**Comment by starpit** [comment]
seems good for now. we should queue up work to figure how out how to do this in a theme-neutral way

**Pull request merged**
