### PR TITLE
feat: use last stable Node.js everywhere

### PR DESCRIPTION
**Pull request by jesusprubio**

### CODE REVIEW

**Comment by starpit** [comment]
Is this solving a problem? I thought it would be good to continue ensuring node8 conformance, at least for a while longer.

**Comment by starpit** [comment]
Maybe to start with we can change this to node8? It would be good to have this constraint expressed in our package.json!

**Comment by jesusprubio** [comment]
This is the plan for Node.js releases, v10 is the stable now:

image

I think we need to choose carefully, having in account the extra work we need to support different versions. As you know, Node.js is not backwards compatible if we want to use the new features, so it's not trivial.

**Comment by starpit** [comment]
Agreed with limiting support, but we aren't yet using any node 10 features. And node does ensure forwards compatibility, don't they?

**Comment by jesusprubio** [comment]
Yes, it ensures forwards, not backwards. In example:

image

About the v10 features, it includes some interesting things: https://www.creativebloq.com/advice/whats-new-in-nodejs-10

**Comment by starpit** [comment]
i strongly suggest that we change this to specify node8. this should also resolve https://github.com/IBM/kui/issues/1406

**Pull request closed without merging**
