### PR TITLE
fix: Update kubectl-kui location on macOS to inside Kui.app/Contents/Resources

### PR DESCRIPTION
**Pull request by LouisStAmour**
#### Description of what you did:

This change is suggested because I'm submitting a Cask to Homebrew and would like to include the kubectl-kui binary in /usr/local/bin directly while installing the application to /Applications. 

Additionally, I ran by habit "kubectl kui get pods" from inside Kui and it appeared to hang indefinitely. This script prevents that, though it doesn't produce pretty output like Kui normally would.

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

**Comment by starpit** [comment]
thanks for the PR! we will check it out!

**Comment by LouisStAmour** [comment]
No problem! Glad to help. As noted in the other issues/open PRs, when this merges, we can update the homebrew "kui.rb" file to remove the comment next to the "binary" line and update the "caveats" line to remove references to adding to PATH as that won't be necessary. https://github.com/Homebrew/homebrew-cask/pull/84210

**Comment by LouisStAmour** [comment]
To update my above comment, as the cask reviewers did not like my commented TODO and caveats section, if we later want to include the installation of kubectl-kui binary in /usr/local/bin, we'll have to add `binary 'Kui-darwin-x64/kubectl-kui'` below the `app` line once this is merged and released.

**Comment by starpit** [comment]
thanks again for the work on this. is it possible for the kui cask to use the `target` option? e.g.

```
  app 'Kui-darwin-x64/Kui.app'
  binary 'Kui-darwin-x64/kubectl-kui-for-cask', target: 'kubectl-kui'
```

then, we could have a `kubectl-kui-for-cask` script that is specific to a /Applications installation. that script could then be simpler, as it could be hard-coded to a /Applications installation site.

as it stands with your PR, if a user were to download a version of Kui by hand (i.e. not using brew), and they happened to have an older version in /Applications... then out of the box, the kubectl-kui would point to the older version of Kui, not the version they just downloaded.

whereas, if we could keep the two separate: have one kubectl-kui which assumes Kui.app is a sibling, and another which assumes it is in /Applications... thoughts?

**Comment by LouisStAmour** [comment]
Well, my original intent was to change the script to look for the local copy first and only use /Applications if there wasn’t a local copy. But it’s very rare to not have Applications on macOS run from local folders. Common practice puts applications in ~/Applications or /Applications by default. So the script isn’t perfect in searching for local app folders. I am somewhat making an assumption that if you want to install the app in a non-standard location on Darwin that you’ll be able to edit this shell script launcher to reflect the new path.

The reason I didn’t follow the above approach initially was because getting the directory of the script location was implemented by changing the current directory to the script path. It didn’t make sense to cd to /Applications, and I’m not sure CD to /usr/local/Cellar... where Homebrew installs by default makes sense either.

That said, I could modify the script to capture pwd before it performs the cd and then cd back to the old pwd if it finds a copy at /Applications? I could also add a check for ~/Applications? I’m not sure if there are any side-effects that rely on the cd?

Any thoughts on the KUI=true hack to avoid an infinite loop? (Presumably?) Is there a nicer way of doing that?

**Comment by LouisStAmour** [comment]
For example:

https://docs.vmware.com/en/VMware-Fusion/11/com.vmware.fusion.using.doc/GUID-E49097CB-505E-4F52-9359-F7DECB9254BC.html

or

https://github.com/Homebrew/homebrew-cask/search?q=contents+binary&unscoped_q=contents+binary

**Comment by starpit** [comment]
Thanks for the clarification!

I think we can go one of two ways?

1) One script, but check for a sibling installation of Kui.app first, with a backup that looks in /Applications.

2) Two scripts, one that always looks in sibling (which is how it works prior to this discussion)

Your PR in its current form looks in /Applications first, and uses sibling as a backup. This breaks the use case of someone downloading and using Kui v2 from e.g. their Downloads directory, but having a prior Kui v1 in /Applications. With either of the above approaches, i think we can support all of these use cases:

a) brew install kui, and use kubectl-kui from /usr/local/bin
b) download Kui from github and use from wherever
c) a then b
d) b then a

The reason I was leaning towards approach #2 (two scripts) is to help with a fifth use case:

e) both a and b, and the user wants the kubectl-kui in /usr/local/bin always to point to whatever was last installed by brew, and wants the kubectl-kui in their downloads directory always to point to what they just downloaded.

I'm not sure I quite understood your questions about cd'ing? Were you referring to the `$(cd ...)` bits of the scripts?

Re: infinite loops. let me think a bit more on that!

**Comment by starpit** [comment]
i see, re: the hang. this seems to be due to the `&` in the script. if i remember correctly, the node-pty module has some issues on macos with job control. so i think the problem can be solved by only backgrounding if KUI is not set!

**Comment by LouisStAmour** [comment]
What would you think of embedding the script inside the .app?

As I wrote earlier:

>If you have a binary that ships with an app, common practice is to embed all binary scripts into the .app itself, distributing one file that contains more utilities. An example would be the launching of the macOS app from inside its own .app folder. Packaging extra utilities outside an .app, then, is relatively rare.

Examples of this include:

https://docs.vmware.com/en/VMware-Fusion/11/com.vmware.fusion.using.doc/GUID-E49097CB-505E-4F52-9359-F7DECB9254BC.html

and from Homebrew:

https://github.com/Homebrew/homebrew-cask/search?q=contents+binary&unscoped_q=contents+binary

**Comment by starpit** [comment]
howdy! i am indeed open to placing a script inside of the Contents/MacOS directory.

**Comment by LouisStAmour** [comment]
Okay, I’ll work out a prototype taking into account your above feedback and update the PR :)

I can’t wait to tell coworkers next week to just “brew cask install kui” and have it all work, including the kubectl plugin. ;-)

**Comment by starpit** [comment]
indeed! (fyi: we have a few bug fixes for "popup" mode in flight now)

**Comment by LouisStAmour** [comment]
I was about to say:

> Updated to publish the script inside `Kui.app` on the Mac build, specifically at `Kui.app/Contents/Resources/kubectl-kui`
> 
> After this merges and is released, I'll update the Homebrew cask to include the above binary when you install the cask. For now, you could do `ln -s /Applications/Kui.app/Contents/Resources/kubectl-kui /usr/local/bin/kubectl-kui` to try it.

But then I tried it and it didn't work as expected. Give me a sec to work out a fix. :)

**Comment by LouisStAmour** [comment]
Okay, that was a lot more work than I expected, but now I can say that the script can be run (on Mac, at least) from either the Kui.app directly, or via symlink as in my earlier note:

Updated to publish the script inside Kui.app on the Mac build, specifically at `Kui.app/Contents/Resources/kubectl-kui`

After this merges and is released, I'll update the Homebrew cask to include the above binary when you install the cask. For now, you could do `ln -s /Applications/Kui.app/Contents/Resources/kubectl-kui /usr/local/bin/kubectl-kui` to try it.

**Comment by LouisStAmour** [comment]
Gah I'm getting sick of this PR. Okay, somehow everything worked until I built it and copied the app into /Applications/, then it stopped working. So let's hit "pause" and try again...

**Comment by LouisStAmour** [comment]
Okay, that was a lot more work than I expected, but now I can say that the script can be run (on Mac, at least) from either the Kui.app directly, or via symlink:

Updated to publish the script inside Kui.app on the Mac build, specifically at `Kui.app/Contents/Resources/kubectl-kui`

After this merges and is released, I'll update the Homebrew cask to include the above binary when you install the cask. For now, you could do `ln -s /Applications/Kui.app/Contents/Resources/kubectl-kui /usr/local/bin/kubectl-kui` to try it.

**Comment by starpit** [comment]
wow, your latest change is very nice, thanks!

**Comment by starpit** [comment]
how should we manage updating the cask recipe?

**Comment by LouisStAmour** [comment]
Well, I guess my thinking is: 

merge this, release a new version, nobody’s using the cask yet so don’t worry about documenting changes for existing users beyond those wondering where the script went on macOS... 

submit PR to casks repo to add binary line against updated release. Wait for PR merge. 

Once cask PR is merged, edit Github release notes (if possible?) to include instructions on how to use the new cask, that it will install the app to your Applications folder and also provide a sun link in /usr/local/bin to kubectl-kui so out of the box after running “brew cask install kui” you’ll get both set up and ready to use. 

Later, update website and documentation in a later PR to reflect the new instructions once everything works. :)

**Comment by LouisStAmour** [comment]
As to ongoing updates of the cask, as long as the file name in the GH release doesn’t change except to match version number, the Github atom feed I included will be checked roughly once a day by a community effort and PRs to bump versions will be submitted automatically.

**Comment by starpit** [comment]
that's great.

also, we have had a request for an "udpate is available" notifier #4573  and an associated PR (as of this writing unmerged) #4892 

will we need to align installed-via-cask with updated-via-cask? at the moment, the PR refers users to github, when an update is available.

**Comment by LouisStAmour** [comment]
If we handle upgrades automatically, we can hint at this using `auto_updates` in the cask. This is used by third party tools like https://github.com/buo/homebrew-cask-upgrade though they aren’t necessarily common. Most folks install via cask so they can update with one command, often even if the app ships with an updater since updates aren’t always reliable.

We can have a standard note that the new release will be published shortly to homebrew. That said, because everything is in one app package, the traditional way to install updates is to download a .dmg image, drag the app from the dmg to the Applications shortcut and overwrite the previous install. This action still works with casks, except you’re choosing not to use the cask. That’s okay—everything still works, even the symlink the cask will set up.

**Comment by starpit** [comment]
sounds good. we do have the ability to build DMGs. we aren't yet distributing them, since this requires building on macOS.

**Comment by starpit** [comment]
note for the future: once this is merged and the builds have reached github, we will need to update the READMEs. They will need to be updated to reflect the new PATH to kubectl-kui for macOS

**Comment by LouisStAmour** [comment]
> sounds good. we do have the ability to build DMGs. we aren't yet distributing them, since this requires building on macOS.

https://github.com/sporsh/docker-create-dmg might be an option for future investigation. And https://hub.docker.com/r/bruienne/pkgsign/

That said, changing to build on Mac, such as with GitHub Actions might be an option...

**Comment by starpit** [comment]
thanks for the pointers!

**Comment by starpit** [comment]
we will release 8.9.4 soon which will be the first builds with this change.

**Comment by starpit** [comment]
8.9.4 is out

**Pull request merged**
