### PR TITLE
style(plugins-proxy-support): lint unused-vars

### PR DESCRIPTION
**Pull request by jesusprubio**
#### Please confirm that your PR fulfills these requirements
- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

**Comment by jesusprubio** [comment]
> Thanks, we shouldn't have have .eslintrc.json in every plugin. The other changes look good.

We should until we can drop these files and enable de rule in the last one.

**Comment by myan9** [comment]
> > Thanks, we shouldn't have have .eslintrc.json in every plugin. The other changes look good.
> 
> We should until we can drop these files and enable de rule in the last one.

I see, thanks! Should we also consider using the override mechanism and changing the root eslintrc.json only?
https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files

**Comment by jesusprubio** [comment]
> > > Thanks, we shouldn't have have .eslintrc.json in every plugin. The other changes look good.
> > 
> > 
> > We should until we can drop these files and enable de rule in the last one.
> 
> I see, thanks! Should we also consider using the override mechanism and changing the root eslintrc.json only?
> https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files

Yes, we have considered all the options. Honestly, I 'm only interested in fixing the linting problems as soon as possible.

If you prefer I can change it in all PRs (there are a lot).  But I don't think the alternative to choose is something important here because we're going to drop these involved lines.

**Comment by myan9** [comment]
> > > > Thanks, we shouldn't have have .eslintrc.json in every plugin. The other changes look good.
> > > 
> > > 
> > > We should until we can drop these files and enable de rule in the last one.
> > 
> > 
> > I see, thanks! Should we also consider using the override mechanism and changing the root eslintrc.json only?
> > https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files
> 
> Yes, we have considered all the options. Honestly, I 'm only interested in fixing the linting problems as soon as possible.
> 
> If you prefer I can change it in all PRs (there are a lot). But I don't think the alternative to choose is something important here because we're going to drop these involved lines when we finish with this rule.

ok!

**Comment by starpit** [comment]
lgtm except for merge conflcits?

**Comment by starpit** [comment]
closing in favor of #1638 which fixes the typecov regressions (false positives, but a good excuse to add some types)

**Pull request closed without merging**
