### PR TITLE
Replace TSLint with ESLint

### PR DESCRIPTION
**Pull request by abdonrd**
Replace TSLint with ESLint.

Also add the `lint-staged` pre-commit hook.

### CODE REVIEW

**Comment by starpit** [comment]
looks good so far!

**Comment by abdonrd** [comment]
@starpit I think we can start with this, and continue removing all the custom `@typescript-eslint` rules in following PRs.

**Comment by starpit** [comment]
the Object -> Record<string,any> change is probably the cause for the typecov regression. this particular change seems a bit suspicious to me, as it isn't actually improving the type clarity of the code. the underlying problem here is that we are missing a type specification.

two solutions:
1) we could have a separate PR to replace those Object types with any. then this PR would not be a regression (nor an improvement) of the type clarity.

2) we could have a separate PR to replace those Object types with meaningful type specs

**Comment by abdonrd** [comment]
Updated with the missed standard and restore the `@typescript-eslint/ban-types` rule!

**Pull request merged**
