### PR TITLE
fix(plugins/plugin-editor): A11y - fix sidecar editor tooltip contrast issue

### PR DESCRIPTION
**Pull request by showeimer**
Fixes https://github.com/IBM/kui/issues/3075

#### Description of what you did:

Before:
Screen Shot 2019-10-22 at 3 37 58 PM

After:
Screen Shot 2019-10-22 at 3 37 48 PM

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

**Comment by starpit** [comment]
we'll have to find a way to integrate this with the themes. i'll look

**Comment by showeimer** [comment]
@starpit seems like all the themes use the gray tooltip box, are we wanting that to be different for each theme?

**Comment by starpit** [comment]
i think maybe
```
  background-color: var(--color-base05);
  color: var(--color-base01) !important;
```

**Comment by starpit** [comment]
or maybe better
```
background: var(--color-sidecar-toolbar-background);
color: var(--color-sidecar-toolbar-foreground);
```

**Pull request merged**
